# 1. 1d Array

In [9]:
import numpy as np
# Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

In [8]:
# Calculate the sum and average of the array elements.
sum_array = sum(a)
print(f"Sum is {sum_array}")
avg_array = sum_array/len(a)
print(f"Average is {avg_array}")


Sum is 55
Average is 5.5


In [6]:
avg_array = sum_array/len(a)
print(avg_array)

5.5


In [13]:
# Slice the array to select elements from the 3rd to the 7th position.
sliced_array = a[2:8]
print(sliced_array)

[3 4 5 6 7 8]


In [18]:
# Compute the sum and average of the sliced array
sliced_sum = sum(sliced_array)
print(sliced_sum)
sliced_avg = sliced_sum/(len(sliced_array))
print(sliced_avg)

33
5.5


# 2. Multi-dimensional array

In [19]:
# Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}
matrix_33 = np.array([[3,4,5],[6,7,8],[9,1,2]])
print(matrix_33)

[[3 4 5]
 [6 7 8]
 [9 1 2]]


In [27]:
# Print the element in the second row, third column.
element = matrix_33[1, 2]
print(element)

8


In [29]:
# Print the second row
row2 = matrix_33[1,:]
print(row2)

[6 7 8]


In [31]:
# Print the second column
col2 = matrix_33[:,1]
print(col2)

[4 7 1]


In [32]:
# Compute the transpose of the matrix
trans_matrix = np.transpose(matrix_33)
print(trans_matrix)

[[3 6 9]
 [4 7 1]
 [5 8 2]]


# 3. Concatenation

In [33]:
# Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]
array1 = np.array([5, 1, 4, 2])
array2 = np.array([6, 10, 11, 7])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [5 1 4 2]
Array 2: [ 6 10 11  7]


In [34]:
# Concatenate the two arrays
concat_array = np.concatenate((array1, array2))

print("Concatenated Array:", concat_array)

Concatenated Array: [ 5  1  4  2  6 10 11  7]


In [35]:
# Sort the new array from lowest to highest
sorted_array = np.sort(concat_array)
print("Sorted Array:", sorted_array)

Sorted Array: [ 1  2  4  5  6  7 10 11]


In [36]:
# Split the result from the previous step into two equal sized arrays
split_arrays = np.split(sorted_array, 2)
print("Split Arrays:", split_arrays)

Split Arrays: [array([1, 2, 4, 5]), array([ 6,  7, 10, 11])]


# 4. Mathematical functions

In [47]:
# Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
pi = 3.14
piarray = np.arange(0, (pi*4 + pi/2), pi/2)
print(piarray)

[ 0.    1.57  3.14  4.71  6.28  7.85  9.42 10.99 12.56]


In [51]:

piarray = np.arange(0, (np.pi*4 + np.pi/2), np.pi/2)
print(piarray)

[ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061]


In [52]:
# Compute an array that applies the mathematical sin function to the original array
sin_arr = np.sin(piarray)
print("Sin Array:", sin_arr)

Sin Array: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16  1.0000000e+00  3.6739404e-16 -1.0000000e+00
 -4.8985872e-16]


In [53]:
# Do the same for the following mathematical functions: cos, log, exp
cos_arr = np.cos(piarray)
print("Cos Array:", cos_arr)
log_arr = np.log(piarray)
print("Log Array:", log_arr)
exp_arr = np.exp(piarray)
print("Exp Array:", exp_arr)

Cos Array: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00  3.0616170e-16 -1.0000000e+00 -4.2862638e-16
  1.0000000e+00]
Log Array: [      -inf 0.45158271 1.14472989 1.55019499 1.83787707 2.06102062
 2.24334217 2.39749285 2.53102425]
Exp Array: [1.00000000e+00 4.81047738e+00 2.31406926e+01 1.11317778e+02
 5.35491656e+02 2.57597050e+03 1.23916478e+04 5.96097415e+04
 2.86751313e+05]


/var/folders/80/wdc67jbn5t595hmj0r1v6jhw0000gn/T/ipykernel_21921/14452726.py:4: RuntimeWarning: divide by zero encountered in log
  log_arr = np.log(piarray)


In [54]:
# Compute the mean, median, and standard deviation of each resultant array
def mean(array):
    mean_value = np.mean(array)
    return mean_value
def median(array):
    median_value = np.median(array)
    return median_value
def std_dev(array):
    std_dev_value = np.std(array)
    return std_dev_value

print("Mean of pi array", mean(piarray))
print("Median of pi array", median(piarray))
print("Satndard Deviation of pi array", std_dev(piarray))
print("Mean of Sin array", mean(sin_arr))
print("Median of Sin array", median(sin_arr))
print("Satndard Deviation of Sin array", std_dev(sin_arr))
print("Mean of Cos array", mean(cos_arr))
print("Median of Cos array", median(cos_arr))
print("Satndard Deviation of Cos array", std_dev(cos_arr))
print("Mean of Logarithm array", mean(log_arr))
print("Median of Logarithm array", median(log_arr))
print("Satndard Deviation of Logarithm array", std_dev(log_arr))
print("Mean of Exponential array", mean(exp_arr))
print("Median of Exponential array", median(exp_arr))
print("Satndard Deviation of Exponential array", std_dev(exp_arr))

Mean of pi array 6.283185307179587
Median of pi array 6.283185307179586
Satndard Deviation of pi array 4.055778675973612
Mean of Sin array -2.975712385932333e-17
Median of Sin array 0.0
Satndard Deviation of Sin array 0.6666666666666666
Mean of Cos array 0.11111111111111106
Median of Cos array 6.123233995736766e-17
Satndard Deviation of Cos array 0.7370277311900889
Mean of Logarithm array -inf
Median of Logarithm array 1.8378770664093453
Satndard Deviation of Logarithm array nan
Mean of Exponential array 40222.7148375631
Median of Exponential array 535.4916555247646
Satndard Deviation of Exponential array 89056.36419225672


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/_methods.py:173: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


# 5. Boolean Indexing and Filtering

In [60]:
# Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
multi_array = np.arange(15, 81, 5)
new_multi_array =np.sort(np.append(multi_array, 12))
print(new_multi_array)

[12 15 20 25 30 35 40 45 50 55 60 65 70 75 80]


In [61]:
# Create a boolean array that identifies elements which are greater than 25
boolean_arr = new_multi_array > 25
print(boolean_arr)

[False False False False  True  True  True  True  True  True  True  True
  True  True  True]


In [65]:
# Use that boolean array to filter out elements greater than 25 from the original array.
fil_arr = new_multi_array[~boolean_arr]
print(fil_arr)

[12 15 20 25]
